Sources/Accord.MachineLearning/DecisionTrees/Learning/C45Learning.cs
Unit Tests/Accord.Tests.MachineLearning/DecisionTrees/C45LearningTest.cs

This is fix for issue #57: C4.5Learning: tree depends on the sorting order when the decision variable is continuous.

C45Learning splitting threshold selection fix

---

Sources/Accord.Math/Tools.cs

When compiling for Mono, the `ThreadLocal<T>(Func<T> valueFactory, bool
trackAllValues)` constructor currently throws when `trackAllValues =
true`. To workaround this issue, the `random` variable is re-initialized
with a more fail-safe constructor if the first initalization throws.
[Reference](https://github.com/cureos/accord/issues/11)
Hi César,
this pull request is made from my "pull request" fork, which is identical to your main fork except for the pull request code. It should thus be straightforward to make the pull if you want to. Many thanks for your suggestion on how to solve this issue; way better than my own approach :-)
Best regards,
Anders

Accord.Math/Tools.cs: Handle temporary lack of support in Mono runtime

---

Unit Tests/Accord.Tests.Audio/ComplexSignalTest.cs
Unit Tests/Accord.Tests.MachineLearning/RansacLineTest.cs
Unit Tests/Accord.Tests.Math/Geometry/ConvexHullDefectsTest.cs
Unit Tests/Accord.Tests.Math/Matrix/MatrixTest.cs
Unit Tests/Accord.Tests.Statistics/Analysis/CircularDescriptiveAnalysisTest.cs
Unit Tests/Accord.Tests.Statistics/Analysis/DescriptiveAnalysisTest.cs
Unit Tests/Accord.Tests.Statistics/Analysis/LogisticRegressionAnalysisTest.cs
Unit Tests/Accord.Tests.Statistics/Analysis/MultinomialLogisticRegressionAnalysisTest.cs
Unit Tests/Accord.Tests.Statistics/Analysis/MultipleLinearRegressionAnalysisTest.cs
Unit Tests/Accord.Tests.Statistics/Analysis/ProportionalHazardsAnalysisTest.cs
Unit Tests/Accord.Tests.Statistics/Distributions/Univariate/Continuous/CauchyDistributionTest.cs
Unit Tests/Accord.Tests.Statistics/Distributions/Univariate/Continuous/ChiSquareDistributionTest.cs
Unit Tests/Accord.Tests.Statistics/Distributions/Univariate/Continuous/GompertzDistributionTest.cs
Unit Tests/Accord.Tests.Statistics/Distributions/Univariate/Continuous/InverseChiSquareDistributionTest.cs
Unit Tests/Accord.Tests.Statistics/Distributions/Univariate/Continuous/InverseGaussianTest.cs
Unit Tests/Accord.Tests.Statistics/Distributions/Univariate/Continuous/LogNormalDistributionTest.cs
Unit Tests/Accord.Tests.Statistics/Filters/CodificationFilterTest.cs
Unit Tests/Accord.Tests.Statistics/Filters/NormalizationFilterTest.cs
Unit Tests/Accord.Tests.Statistics/Filters/ProjectionFilterTest.cs
Unit Tests/Accord.Tests.Statistics/Testing/OneWayAnovaTest.cs

Hi César,
this is a little bit selfish of me :-), but it would make it easier for me to keep the unit tests in the portable Accord.NET repository in sync with your main repository if you would accept this pull request.
There are a number of otherwise non-UI unit tests where you have prepared for using some of the controls in the `Accord.Controls` namespace. The usage is however commented away, for example like this:
//ImageBox.Show(image);
but the corresponding `using` cirective is still present in the file header:
using Accord.Controls;
Since the controls in the `Accord.Controls` namespace are *Windows Forms*  controls, I have made no attempt of porting them to the portable repository.
Thus, when I try to build a unit test with the normally unused `using Accord.Controls` directive in the …

Removed unused Accord.Controls and System.Drawing usings

---

Sources/Accord.Core/AForge/PolishExpression.cs
Unit Tests/Accord.Tests.Math/Accord.Tests.Math.csproj

Hi Cesar,
this may seem like a silly pull request, but here is a minor change of the recently added *AForge* code that improves type safety by using the generic `Stack<double>` instead of `Stack`.
The primary reason why I'd like to see this change is of course to facilitate porting *Accord.NET* to PCL :-) The non-generic `Stack` type is not available in PCL, whereas `Stack<T>` is.
Thanks in advance!
Anders

Re-factor arguments into Stack<double>

---

Sources/Accord.Genetic/Chromosomes/GP/GEPChromosome.cs

Hello again César!
Here is another minuscule pull request that will make the imported *AForge* code more portable and improve type safety. Once again, the request is primarily valuable to my PCL fork, but I hope should have at least some added value to your main fork as well.
Thanks in advance!
Anders

Use generic queue type to increase portability

---

Sources/Accord.Audio/Filters/EnvelopeFilter.cs

EnvelopeFilter was not working because the loop variables were not being incremented.

fixed missing loop variables.

---

Sources/Accord.MachineLearning/Clustering/KMeans.cs

Hello Cesar,
I'm developing spectral clustering for an application and needed Weighted K-Means so I figured I should push it in. If not weights are added then it should work as previous, otherwise it is pretty straight forward weighted mean calculation of centroids instead of mean.
No negative weights allowed

Modified K-Means to support Weighted K-Means

---

Sources/Accord.Math/Vector/Vector.Scale.cs

If fromMin = fromMax, then no change should take place, and we should return the same values we received. Otherwise, a division by 0 occur that ultimately returns all NaN values.

Update Scale Algorithm

---

Sources/Accord.Video.DirectShow/Internals/Uuids.cs
Sources/Accord.Video.DirectShow/VideoCaptureDevice.cs

...to specify PixelFormat for SampleGrabber
also fixed some typos

add constructor to VideoCaptureDevice and Grabber

---

Sources/Accord.MachineLearning/VectorMachines/Learning/OneclassSupportVectorLearning.cs

Fixes issue #271.
The private `shrinking` field, which was not in use anywhere, is now used in the `FanChenLinQuadraticOptimization` created in the `OneclassSupportVectorLearning.Learn` method.

Fix one class svm to use shrinking heuristics.

---

Sources/Accord.Statistics/Models/Regression/Linear/MultipleLinearRegression.cs

MultipleLinearRegression.Regress(double[][], double[], bool) was ignoring last parameter instead of passing it further.

Fix ignored `robust` param in MultipleLinearRegression.Regress

---

Sources/Accord.Math/Distances/Hamming.cs

In the `Hamming.Distance` method, the [`BitArray.Count`](https://msdn.microsoft.com/en-us/library/system.collections.bitarray.count.aspx) property getter has been used. This property is unfortunately .NET Framework specific and is **not** generally applicable to other C# based platforms like the *Universal Windows Platform*.
To facilitate building *Accord.Math* as a Portable Class Library (like in *Portable Accord* [here](https://github.com/cureos/accord)) it is therefore recommended that the `BitArray.Count` getter is replaced with the equivalent and portable [`BitArray.Length`](https://msdn.microsoft.com/en-us/library/system.collections.bitarray.length.aspx) getter.
This pull request contains a replacement of `BitArray.Count` with `BitArray.Length`.

Use BitArray.Length instead of BitArray.Count

---

Sources/Accord.MachineLearning/Structures/KDTreeNodeDistance.cs

In the general `KDTreeNodeDistance<T>.CompareTo(object)` method, the following comparison with the field `distance` and the parameter `obj` is currently being made:
return distance.CompareTo((KDTreeNodeDistance<T>)obj);
But since `distance` is a `double` this is effectively the same as calling:
return distance.CompareTo((object)obj);
The correct call would instead be to dispatch the comparison to the specific `CompareTo` method defined in the same class:
return CompareTo((KDTreeNodeDistance<T>)obj);
This pull request provides the aforementioned correction.

In CompareTo(object), call CompareTo(KDTreeNodeDistance<T>)

---

Sources/Accord.MachineLearning/Collections/KDTreeNodeCollection.cs

Currently, the enumerator uses `position.Length` to determine how many items to iterate over.  This results in the enumerator returning objects that don't exist if the collection isn't full (as can happen when using `Nearest(location, radius, maxCount)` on a `KDTree`).
This fix changes the enumerator to use the already-existing `count` variable, which ought to prevent it from returning non-existent collection elements.

Fix Enumerator returned from KDTreeNodeCollection

---

Sources/Accord.Math/Matrix/Jagged.Common.cs

I get some pretty unexpected results when trying to transpose a non-rectangular matrix; where the number of elements in each row aren't the same.

Added a check if matrix is rectangular before transposing

---

Sources/Accord.Math/AForge.Math/Geometry/GrahamConvexHull.cs

Previously submitted to AForge.NET repo @ https://github.com/andrewkirillov/AForge.NET/pull/22 but then saw that it seems to be maintained here now :) 
This is purely an optimisation, and in no way intends to change the behavior of the algorithm.  
The implementation of a Graham Scan is currently using lists internally. The algorithm removes elements from these lists at points other than the end, which can be a very expensive operation. This PR changes the internal collections used to be better suited to the operations performed on them.

Optimise data structures being used by Graham Convex Hull implementation

---

Sources/Accord.Controls.Imaging/AForge/ColorSlider.cs

ColorSlider constructor uses a string constant to access resources within folders. Error is fixed by following the project solution's folder structure.

ColorSlider component resource path's fix. fixes #604

---

Sources/Accord.Core/Serializer.cs
Unit Tests/Accord.Tests.Core/SerializerTest.cs

In this PR I fixed #673: explicitly set `leaveOpen` attribute for [GZipStream](https://msdn.microsoft.com/en-us/library/27ck2z1y(v=vs.90).aspx)  to `true`.

Underlying stream doesn't close after serialization with GZip compression

---

Sources/Accord.Math/Optimization/Constrained/Constraints/LinearConstraint.cs
Unit Tests/Accord.Tests.Math/Optimization/LinearConstraintTest.cs

Hi @cesarsouza,
Pull request to (partially) address the issue with the gradient being of incorrect size when indices are used. I know we spoke about the possibility of changing to use sparse and dense but, as a short-term fix I have simply implemented (a variation on) your proposal from earlier.
>  maybe one possibility to provide a correct, but still fast, version of the gradient method would be to cache the gradient vector after the first call to Gradient. The problem with that is that it wouldn't work in case the users modifies the vector referenced by the `CombinedAs` property directly, without using the property itself. 
I've gone for this but with a slight variation; if the indices are the default {0, 1, 2, 3, ..., n }, then I simply point to the `CombinedAs` vector. In this way, if …

GH-871: Bug in linear constraint gradient - vector has incorrect dimensions

---

Sources/Accord.Math/Decompositions/EigenvalueDecomposition.cs
Sources/Accord.Math/Decompositions/EigenvalueDecomposition.tt
Sources/Accord.Math/Decompositions/EigenvalueDecompositionF.cs
Sources/Accord.Math/Decompositions/JaggedEigenvalueDecomposition.cs
Sources/Accord.Math/Decompositions/JaggedEigenvalueDecomposition.tt
Sources/Accord.Math/Decompositions/JaggedEigenvalueDecompositionF.cs
Sources/Accord.Math/Decompositions/JaggedQrDecomposition.cs
Sources/Accord.Math/Decompositions/JaggedQrDecomposition.tt
Sources/Accord.Math/Decompositions/JaggedQrDecompositionD.cs
Sources/Accord.Math/Decompositions/JaggedQrDecompositionF.cs
Sources/Accord.Math/Decompositions/JaggedSingularValueDecomposition.cs
Sources/Accord.Math/Decompositions/JaggedSingularValueDecomposition.tt
Sources/Accord.Math/Decompositions/JaggedSingularValueDecompositionD.cs
Sources/Accord.Math/Decompositions/JaggedSingularValueDecompositionF.cs
Sources/Accord.Math/Decompositions/QrDecomposition.cs
Sources/Accord.Math/Decompositions/QrDecomposition.tt
Sources/Accord.Math/Decompositions/QrDecompositionD.cs
Sources/Accord.Math/Decompositions/QrDecompositionF.cs
Sources/Accord.Math/Decompositions/SingularValueDecomposition.cs
Sources/Accord.Math/Decompositions/SingularValueDecomposition.tt
Sources/Accord.Math/Decompositions/SingularValueDecompositionD.cs
Sources/Accord.Math/Decompositions/SingularValueDecompositionF.cs
Unit Tests/Accord.Tests.Math/Decompositions/EigenvalueDecompositionTest.cs
Unit Tests/Accord.Tests.Math/Decompositions/JaggedEigenvalueDecompositionTest.cs
Unit Tests/Accord.Tests.Math/Decompositions/JaggedQrDecompositionTest.cs
Unit Tests/Accord.Tests.Math/Decompositions/JaggedSingularValueDecompositionTest.cs
Unit Tests/Accord.Tests.Math/Decompositions/QrDecompositionTest.cs
Unit Tests/Accord.Tests.Math/Decompositions/SingularValueDecompositionTest.cs

As discussed in #882:
> The LuDecomposition and CholeskyDecomposition classes expose properties with a simple Lazy evaluation pattern on the factored matrices. The QrDecomposition does not do this. Any unsuspecting user attempting to iterate through, say, the UpperTriangleFactor directly is in for a nasty shock as the matrix could potentially be rebuilt thousands of times.
> 
> Propose lazy cache on QR properties (or method call if caching undesirable). On phone but can post code snippet later if this is not clear. SVD has a few issues as well.
Fixed a few others and added checks in the unit test, `Assert.AreSame()` to check instance equality.
Thanks,
Alex
This closes #882

GH-882: QR Decomposition not caching work intensive properties

---

Sources/Accord.Math/Random/ZigguratNormalGenerator.cs
Unit Tests/Accord.Tests.Math/Accord.Tests.Math.csproj
Unit Tests/Accord.Tests.Math/Random/ZigguratNormalGeneratorTest.cs

Fix for GH-921. Simple fix where the logic to initialise the  `ZigguratNormalGenerator` internals are moved into the seeded constructor.
Unit tests in `ZigguratNormalGeneratorTest`

GH-921: Fix for the normal random number generator when a seed is specified

---

Sources/Accord.Video.DirectShow/VideoCaptureDevice.cs

In my setup (regular notebook webcam), I cannot achieve more than 1 fps (!), without setting this field to zero.
Obviously, you can set it to zero, to allow the maximum frame rate achievable by the system, or you can set it to a positive value (in 100 nsec units, to get the desired frame rate), therefore a property could be added.

Allow the maximum frame rate possible

---

Sources/Accord.Math/Optimization/Constrained/Constraints/LinearConstraint.cs
Unit Tests/Accord.Tests.Math/Optimization/LinearConstraintTest.cs

Adding documentation *as is*. Having discussed with you last week, changes to the `LinearConstraint` class are currently on hold (probably until an integer solver exists). I see no reason not to document the `LinearConstraint` in its current guise.
Thanks
A

GH-818: Adding example of how to use a LinearConstraint

---

Sources/Accord.Math/Accord.Math.csproj
Sources/Accord.Math/Optimization/Constrained/AugmentedLagrangian.cs
Sources/Accord.Math/Optimization/Constrained/Constraints/ConstraintExtensions.cs
Sources/Accord.Math/Optimization/Constrained/Constraints/IConstraint.cs
Sources/Accord.Math/Optimization/Constrained/Constraints/LinearConstraint.cs
Sources/Accord.Math/Optimization/Constrained/Constraints/NonlinearConstraint.cs
Unit Tests/Accord.Tests.Math/Optimization/AugmentedLagrangianTest.cs

Hi @cesarsouza,
Went for a fairly simple implementation in the end. I made a few design decisions along the way so if you don't want to go down this route, **please say and I'm 100% happy to change**.
Thanks,
Alex
- I changed all constructors from `IEnumerable<NonlinearConstraint>` to `IEnumerable<IConstraint>`. I don't believe (correct me if wrong) that this is a breaking change as long as you are using C# 4.0+ as `IEnumerable<>` became covariant in that release. It certainly didn't break any unit tests.
- I had to change `IConstraint` from `internal` to `public` for access modifier consistency.
- I had to add `Tolerance` to the interface of `IConstraint` so the `AugmentedLagrangian` could check it. However, I have *not* centralised any checking process on `Tolerance` as of yet so this …

GH-820: Augmented Lagrangian to support linear constraints

---

Sources/Accord.Math/Vector/Vector.Random.cs

Is it ok to add support for Vector sampling with replacement (meaning: sampling from an array with repeating values)?
I have added an extra parameter in the method "T[] Sample<T>", the boolean "replacement" with a default value as false (in order not to affect the existing references that depend on it).
The motivation behind this, is to further support the random forest algorithm, with sampling with replacement:
"If the number of cases in the training set is N, sample N cases at random - but with replacement, from the original data." (Leo Breiman's original source: https://www.stat.berkeley.edu/~breiman/RandomForests/cc_home.htm#overview)

Addition of Vector Sampling with replacement?

---

Sources/Accord.Math/Optimization/Unconstrained/Least Squares/LevenbergMarquardt.cs

Hi there, 
Thanks for this amazing library.
In the current implementation of the Levenberg-Marquardt algorithm, the approximation J^TJ of the Hessian matrix is damped using a \lambda * Identity factor. This is known as the Levenberg contribution, and the resulting algorithm is known as the Levenberg algorithm.
Marquardt contribution consists in damping J^TJ with \lambda * Diagonal, where Diagonal is the Diagonal of J^TJ. I think this factor should be implemented in the Levenberg-Marquardt algorithm.
Information regarding Levenberg and Marquardt contributions are available here : https://en.wikipedia.org/wiki/Levenberg%E2%80%93Marquardt_algorithm
Moreover, using the Marquardt contribution instead of the Levenberg one has a real impact on the convergence of the algorithm: in particular, it …

LevenbergMarquardt: implement the Marquardt contribution in the LevenbergMarquardt algorithm.

---

Sources/Accord.Imaging/AForge.Imaging/Drawing.cs

The original repository doesn't have the ability of setting width of the line of the rectangle marker in face tracking, one method added to make this work.

Add support for the line width setting of the rectangle

---

Sources/Accord.Statistics/Analysis/Performance/ReceiverOperatingCharacteristic.cs
Unit Tests/Accord.Tests.Statistics/Analysis/ReceiverOperatingCharacteristicTest.cs

If the increment is less than or equal to 0, the amount of points added to the curve would be infinite.

Solved infinite loop in ROC curve

---

Sources/Accord.Core/AForge.Core/SystemTools.cs

If running Accord.Imaging under Linux, every conversion of a bitmap to UnmanagedImage calls SetUnmanagedMemory and CopyUnmanagedMemory. Those functions call native Windows functions, thus causing an exception if running e.g. under Linux.
This is fixed by a managed implementation when running under a non-Windows OS. Feel free to replace this by a corresponding call to a Linux / MacOS function.

Fix exception on Windows native memory calls under Linux

---

Sources/Accord.MachineLearning/Clustering/MeanShift/MeanShiftCluster.cs

Hello,
I just fixed #1404 by removing the lock statement. The `lock` statement in there was to provide thread synchonization on `labels` variable, but there were no mutation in the statement, so it was unnecessary.

fixes #1404

---

Sources/Accord.Math/Random/Generator.cs

In the current version of Math/Random/Generator.cs, there is no line to set Generator.threadOverriden to false. Thus once Generator.ThreadSeed is assigned to non-null and threadOverriden is set to true, Generator.Random will return threadRandom permanently. By re-assigning ThreadSeed to null, threadRandom becomes null. As a result, Generator.Random returns null.
This pr will address this issue by resetting threadOverriden to false when ThreadSeed is cleared.
Personally I'm not sure whether threadOverriden is necessary in addition to threadRandom, but it is a matter of refactoring anyway.

Random.Generator.Random returns null when ThreadSeed is set and then cleared

---

Sources/Accord.Math/Matrix/Matrix.Common.cs
Unit Tests/Accord.Tests.Math/Matrix/Matrix.Common.cs

Accord.Math.Matrix.GetSymmetric() always raises IndexOutOfRangeException when used with MatrixType.UpperTriangular because of invalid loop exit condition. This pr will fix this issue.

Fix off-by-one error in Matrix.GetSymmetric

---

Setup/NuGet/Accord.Audio.DirectSound.nuspec

When I install Accord.DirectSound 3.8.2-alpha package to .NET Framework 4.7 project, NuGet installs only the package itself and SharpDX (Figure 1). Other dependent packages, such as Accord.Math and Accord.Audio, are not to be installed.
So I fixed the nuspec file for NuGet to install all expected dependent packages.
Figure 1
Figure 2 shows the packages that will be installed when I install the fixed package to .NET Framework 4.7 project. And Figure 3 shows when .NET Framework 4.0 project.
Figure 2
Figure 3

Fix dependencies of Accord.Audio.DirectSound.nuspec

---

Sources/Accord.Imaging/Filters/HighBoost.cs

Modify the kernel from the public property instead of the private backing field, because that isn't in scope.

Fix a build error

---

.gitattributes
Setup/Scripts/Accord.targets

This makes Accord play nice with Visual Studio's [FastUpToDateCheck](https://github.com/dotnet/project-system/blob/master/docs/repo/up-to-date-check.md).
Right now, VS will always consider every project that references Accord as not up-to-date and will always rebuild it. This PR fixes that by not forcing a file copy (Accord.dll.config) if it's already up-to-date.
I also added `<Visible>false</Visible>` so the file doesn't show up in the solution explorer.

Fix VS FastUpToDate check

---

Sources/Accord.MachineLearning/Collections/VPTree`2.cs

When testing with len-1, points were getting missed.  Changing to Length fixed that
The original c++ code was:
_root = buildFromPoints(0, items.size());
The other VPTree class also used length:
tree.Root = tree.buildFromPoints(points, 0, points.Length, inPlace);

Passing Length instead of Length-1

---

Sources/Accord.Math/IO/Mat/MatNode.cs

This PR fixes an issue that `MatNode.GetValue<T>()` raises ArgumentNullException when passed different type of array (e.g. `ValueType` is `long[,]` and call `GetValue<double[,]>()`).
[Type.GetElementType](https://docs.microsoft.com/en-us/dotnet/api/system.type.getelementtype?redirectedfrom=MSDN&view=netframework-4.8#System_Type_GetElementType) should be used to get the base type of array, so changed `DeclaringType` into `GetElementType`.
In addition fixed an issue by `autoTranspose`.

Fix MatNode.GetValue for different type of array

---

Sources/Accord.Math/Optimization/Munkres.cs

This line in code seems to yield index-out-of-range errors with rectangular matrices. By changing it to use the `Min` of the rowCover or the costMatrix length, the errors are avoided and correct results generated.

Support Rectangular Matrices

---

Setup/Scripts/Accord.Video.FFMPEG.targets

It's annoying to see links to native libs in Visual Studio solution explorer after installing `Accord.Video.FFMPEG` nuget package.
This PR hides link to native libs.

Hide native libs from solution explorer when installing Video.FFMPEG nuget package
