accord-net/framework

Sources/Accord.MachineLearning/Clustering/MeanShift.cs
Sources/Accord.Statistics/Distributions/Density Kernels/GaussianKernel.cs

Gaussian Distribution is -e^(-x^2/2)*x * constant
since x is assumed to be always squared the correct
derivative is -e^(x*0.5)*Math.Sqrt(x) * constant,

Bug in Kernels

---

Sources/Accord.MachineLearning/Clustering/MeanShift.cs
Sources/Accord.Statistics/Distributions/Density Kernels/GaussianKernel.cs

Merged into the wrong branch, should have been merged into one dedicated branch for the issue. Reverts accord-net/framework#68

Revert "Bug in Kernels"

---

Sources/Accord.Statistics/Accord.Statistics.csproj
Sources/Accord.Statistics/Kernels/Hellinger.cs

- New: Hellinger kernel, an euclidean norm of linear kernel.

Hellinger Kernel

---

Sources/Accord.Statistics/Kernels/Pearson.cs

Fixing PUK

---

Samples/Statistics/Survival (Cox)/MainForm.cs
Setup/NuGet/Accord.Video.FFMPEG.nuspec
Sources/Accord.MachineLearning/Clustering/KMeans.cs
Sources/Accord.Math/Formats/Base/MatrixFormatter.cs
Sources/Extras/Accord.Video.FFMPEG.GPL/Video.FFMPEG.vcxproj
Sources/Extras/Accord.Video.FFMPEG.GPL/VideoFileReader.cpp
Sources/Extras/Accord.Video.FFMPEG.GPL/VideoFileReader.h
Sources/Extras/Accord.Video.FFMPEG.GPL/dllmain.cpp
Unit Tests/Accord.Tests.Math/Matrix/Matrix.Format.cs

enhance VideoFileReader frameRate's accuracy
fix Accord.Video.FFMPEG.dll debug build fail "strong name validation failed"
fix nuget package Accord.Video.FFMPEG, "The module specified could not be found"
fix Accord.MachineLearning Xml comment syntax error build break
fix Travis-CI Sample Statistics Survival (Cox) build break
fix Matrix Format ToStringTest, ToStringTest2 Test fail

Accord.Video.FFMPEG enhance

---

Sources/Accord.MachineLearning/Clustering/KMeans.cs

edit kmeans summary

---

Sources/Accord.Statistics/Accord.Statistics.csproj
Sources/Accord.Statistics/Analysis/ProcustesAnalysis.cs
Unit Tests/Accord.Tests.Statistics/Accord.Tests.Statistics.csproj
Unit Tests/Accord.Tests.Statistics/Analysis/ProcrustesAnalysisTest.cs

Hi !
In my spare time I found the Procrustes Analysis and decided to give this a try because it's kind of smart at comparing shapes/datasets with quite good position, scale and rotation abstraction.
So now I want to share this to the community and contribute to this excellent library.
Hope this complies with the coding rules...
Regards,
Remy

Procrustes Analysis

---

Sources/Accord.MachineLearning/DecisionTrees/Pruning/ErrorBasedPruning.cs
Unit Tests/Accord.Tests.MachineLearning/DecisionTrees/ErrorBasedPruningTest.cs

Possible solution of issues:
#234 #235 #236 #237

ErrorBasedPruning issues

---

Samples/Statistics/Classification (MLR)/MainForm.cs

Provided argument doesn't satisfy GetColumns<T>(this T[,] m, int[] index, T[,] result = null); signature

wrong argument

---

Sources/Accord.Neuro/Learning/ParallelResilientBackPropagationLearning.cs

This has faster, more stable convergence and fixes a typo in prior code where layerThresholdDerivatives was being set instead of layerPreviousThresholdDerivatives in S < 0 case.
http://sci2s.ugr.es/keel/pdf/algorithm/articulo/2003-Neuro-Igel-IRprop+.pdf

Upgrade to iRProp+ for faster, more stable convergence

---

Sources/Accord.Math/Optimization/Constrained/GoldfarbIdnani.cs

dmat[i, j] matrix instead of dmat[j, i]
accord-net#171

GoldfarbIdnani QP fix

---

Sources/Accord.MachineLearning/VectorMachines/MulticlassSupportVectorMachine.cs

Revise: Multiple Input Vectors Documentation

---

Sources/Accord.MachineLearning/VectorMachines/Learning/SequentialMinimalOptimization.cs
Unit Tests/Accord.Tests.MachineLearning/VectorMachines/SequentialMinimalOptimizationTest.cs

This issue can be observed by running the test called "Learn_CacheSizeZero_CacheSizeShouldBeZero".

Fixes SMO's CacheSize being overridden

---

Samples/Imaging/Filters (Images)/Filters (Images).csproj
Samples/Imaging/Filters (Images)/MainForm.cs
Samples/Imaging/Filters (Images)/app.config
Sources/Accord.Imaging/AForge.Imaging/Filters/2 Source filters/Divide.cs
Sources/Accord.Imaging/AForge.Imaging/Filters/2 Source filters/Multiply.cs
Sources/Accord.Imaging/AForge.Imaging/Filters/Convolution/FastBoxBlur.cs
Sources/Accord.Imaging/AForge.Imaging/Filters/Other/FastGuidedFilter.cs

[Please see this link :)](https://github.com/accord-net/framework/issues/209)

Fast Guided Filter

---

Samples/Vision/Face detection (Viola-Jones)/MainForm.Designer.cs
Samples/Vision/Face detection (Viola-Jones)/MainForm.cs

Face detection sample is good for me and I wanted to test any image on the sample.
So I added the feature to load image from internet.

Face detection sample: Feature for loading image from internet

---

Sources/Accord.IO/Csv/CsvReader.cs

Fixing #538: CSVReader Ignores specified delimiter

---

Sources/Accord.Video/MJPEGStream.cs

Related to issue #700 and #712 
Reformats MJPEGStream.cs using auto formatting
Improves .NET Standard 2.0 timeout implementation exception handling in MJPEGStream.cs

Reformat and improvements of MJPEGStream.cs

---

Sources/Accord.Math/Optimization/BinarySearch.cs
Unit Tests/Accord.Tests.Math/Optimization/BinarySearchTest.cs

Fix binary search

---

Tools/DebuggerVisualizers/BitmapDataVisualizer.cs
Tools/DebuggerVisualizers/DebuggerVisualizers (2017).csproj
Tools/DebuggerVisualizers/DebuggerVisualizers (2017).sln
Tools/DebuggerVisualizers/HistogramView.Designer.cs
Tools/DebuggerVisualizers/HistogramView.cs
Tools/DebuggerVisualizers/HistogramVisualizer.cs
Tools/DebuggerVisualizers/ImageView.Designer.cs
Tools/DebuggerVisualizers/ImageVisualizer.cs
Tools/DebuggerVisualizers/UnmanagedImageVisualizer.cs

And work with Accord Framework versus AForge.

Updated DebugVisualizers to support Visual Studio 2017

---

Sources/Accord.Math/Matrix/Matrix.Product.tt

Fixing issue with exposing `unsafe` keyword in public API. This closes GH-805.

GH-805: Fixing issue with unsafe keyword being exposed in the public API

---

Sources/Accord.MachineLearning/Clustering/KMeans/MiniBatchKMeans.cs
Unit Tests/Accord.Tests.MachineLearning/Clustering/MiniBatchKMeansTest.cs

Adding the class MiniBatchKMeans and its Unit tests.

Adding Mini-Batch K-Means

---

Sources/Accord.Math/Optimization/Losses/ZeroOneLoss.cs
Unit Tests/Accord.Tests.Math/Accord.Tests.Math.csproj
Unit Tests/Accord.Tests.Math/Losses/LossesTest.cs
Unit Tests/Accord.Tests.Math/Optimization/Losses/LossesTest.cs
Unit Tests/Accord.Tests.Math/Optimization/Losses/ZeroOneLossTest.cs

Hi @cesarsouza,
here is the pull request for #824.
Best regards
Konstantin

Pull request for issue #824.

---

Sources/Accord.Math/Accord.Statistics/Measures.Matrix.Weighted.cs
Sources/Accord.Math/Accord.Statistics/Measures.Vectors.Weighted.cs
Unit Tests/Accord.Tests.Math/Accord.Statistics/MeasuresTest.cs
Unit Tests/Accord.Tests.Math/Accord.Tests.Math.csproj

Hi @cesarsouza ,
Adding exponentially weighted moving average calcs which relates to #884. These numbers have been tested against Python's pandas package and unit tests are in place for all the numbers. This PR provides functionality for exponentially weighted means, variance and covariance.
```python
from pandas import DataFrame
df = pd.DataFrame({'A' : [1, 3, 5, 6, 4, 2, 7, 8, 9, 2, 3, 4, 5, 6, 7],
'B' : [5, 3, 8, 6, 4, 4, 3, 8, 9, 0, 9, 9, 1, 9, 2]})
alpha = 0.5
df.ewm(adjust = True, alpha=alpha).mean()[df.index == 14]
df.ewm(adjust=True, alpha=alpha).cov(bias=True)[14]
```
I've added unit tests in the class `MeasuresTest`. Any questions/comments/critique very welcome.
Thanks,
Alex

GH-884: Time Series analysis support

---

Sources/Accord.Math/Random/ZigguratExponentialGenerator.cs
Sources/Accord.Math/Random/ZigguratNormalGenerator.cs
Sources/Accord.Math/Random/ZigguratUniformOneGenerator.cs
Unit Tests/Accord.Tests.Math/Random/ZigguratNormalGeneratorTest.cs

Fixes to the exponential rng and addressing an issue in debug mode unit testing.
This closes #924 
This fixes #925

[GH-924, GH-925] RNG fixes

---

Sources/Accord.Neuro/Activation Functions/RectifiedLinearFunction.cs

This pull request is related to issue #938

Correct the remarks in document of Rectified linear activation function.

---

Sources/Accord.NET (LGPL-only).sln
Sources/Accord.Video.DirectShow/Accord.Video.DirectShow.cd
Sources/Accord.Video/Accord.Video.cd

Please find attached corrections for issue https://github.com/accord-net/framework/issues/999
I've also corrected some references in class diagram that were still linked to AForge namespace.
Best regards
Michel

Correction of issue #999 for LGPL only solution and corrections in class diagrams

---

Sources/Accord.Video/ScreenCaptureStream.cs

added a reader writer lock to accesses to region field

Allow changing source region for ScreenCaptureStream at runtime

---

.gitignore
Sources/Accord.Math/Special.cs
Sources/Accord.Statistics/Distributions/Univariate/Continuous/MannWhitneyDistribution.cs
Sources/Accord.Statistics/Testing/TwoSample/MannWhitneyWilcoxonTest.cs

The PR is to resolve this issue: https://github.com/accord-net/framework/issues/1327

Fix integer overflow issue for Mann Whitney Wilcoxon Test

---

Sources/Accord.MachineLearning/DecisionTrees/Learning/C45Learning.cs

when a categorical split results in a leaf node without any samples, parent samples will be used instead to generate decision
added attribute "minimum split size" which prevents splitting of nodes when number of samples is > 0 and < minimum split size
added attribute "minimum leaf size" which prevents creating leave nodes when a resulting node (on continuos decision variable) would have less than minimum leaf size samples.

Fixes issue #1659 (leaf nodes without output) and adds attributes "MinimumLeafSize" and "MinimumSplitSize"

---

Sources/Accord.Imaging/AForge.Imaging/Filters/Other/ZhangSuenSkeletonization.cs

Limited stack size may cause a StackOverflowException for large stackalloc. Replace usage with managed memory
Same idea as #1268 which seems to have been inactive for a year. Slight improvements here include CER for the unmanaged memory deallocation

Fix StackOverflowException in ZhangSuenSkeletonization for large images

---

Sources/Accord.Math/Decompositions/NonnegativeMatrixFactorization.cs

An index error has been solved by replacing m -> n.

Index Error

---

Sources/Accord.Video/WindowCaptureStream.cs

I have added the ability to capture a region of a window and not just the entire screen. I kept the same structure as the ScreenCaptureStream but with minor changes.

Added window capture ability

---

Sources/Accord.Imaging/Filters/LineMarker.cs

Un-mirror x-axis in LineMarker

---

Sources/Accord.Video.DirectShow/Accord.Video.DirectShow.csproj
Sources/Accord.Video.DirectShow/Internals/IAMVideoProcAmp.cs
Sources/Accord.Video.DirectShow/VideoCaptureDevice.cs
Sources/Accord.Video.DirectShow/VideoProcAmpProperty.cs

added implementation of IAMVideoProAmp interface and associated methods on VideoCaptureDevice
see issue #303 for details, basically following the formula here: https://github.com/accord-net/framework/issues/303#issuecomment-382520745

add IAMVideoProAmp interface support to VideoCaptureDevice

---

Sources/Accord.Imaging/AForge.Imaging/HoughLineTransformation.cs

Use color parameter when drawing a HoughLine

---

Sources/Accord.Statistics/Analysis/Performance/ConfusionMatrix.cs

`..., pleaseuse ...` -> `..., please use ...`

Updating ConfusionMatrix exception message typo

---

Sources/Accord.Math/Transforms/CosineTransform.cs

Small typo

---

Sources/Accord.Math/Transforms/FourierTransform2.cs

Addresses the inline To Do note about keeping tables in memory.
Tables are recreated only if first use, or if requested with a parameter different from the latest.

Keep trigonometric tables in memory for reuse.
